### ISSUE TITLE
Training model from example then test with another image (larger size)  Resource exhausted: OOM when allocating tensor with shape[1,61,1440,1920,32]

### ISSUE THREAD

**Issue by Nal44** [HenriquesLab/ZeroCostDL4Mic#16]
Hi,

 
I am trying to use your notebook which is really great and easy to use for someone like me without any coding experience.
I did all the testing using the notebook and the example which were fine.
 
Now I want to test if into one on my files but I have some error messages :
My file is a dapi staining (1channel) .tif 
I rename the file starting with stack_channel1.
The only thing is perhaps the size which is much larger compared to the test examples provided, could it be the problem ?
Should I train the model with same larger files ? 
How can I fix the problem ?
 
Could I upload my file somewhere for you to test perhaps ?

Thank you very much!
For info : 

PC: 64gb RAM 
graphic card quadro p2000 8 gb ram

MESSAGE BELOW :

The anthogoes3d network will be used.
Normalizing image channels independently.
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.662228, nms_thresh=0.3.
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-6-16ede791f3d3> in <module>()
     70 for i in range(lenght_of_X):
     71   img = normalize(X[i], 1,99.8, axis=axis_norm)
---> 72   labels, polygons = model.predict_instances(img)
     73 
     74 # Save the predicted mask in the result folder
 
________________________________________
6 frames
________________________________________
/usr/local/lib/python3.6/dist-packages/stardist/models/base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    407         _shape_inst   = tuple(s for s,a in zip(_permute_axes(img).shape, _axes_net) if a != 'C')
    408 
--> 409         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
    410         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label = overlap_label, **nms_kwargs)
    411 
 
/usr/local/lib/python3.6/dist-packages/stardist/models/base.py in predict(self, img, axes, normalizer, n_tiles, show_tile_progress, **predict_kwargs)
    338 
    339         else:
--> 340             prob, dist = predict_direct(x)
    341 
    342         prob = resizer.after(prob, axes_net)
 
/usr/local/lib/python3.6/dist-packages/stardist/models/base.py in predict_direct(tile)
    304         def predict_direct(tile):
    305             sh = list(tile.shape); sh[channel] = 1; dummy = np.empty(sh,np.float32)
--> 306             prob, dist = self.keras_model.predict([tile[np.newaxis],dummy[np.newaxis]], **predict_kwargs)
    307             return prob[0], dist[0]
    308 
 
/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1460                                             verbose=verbose,
   1461                                             steps=steps,
-> 1462                                             callbacks=callbacks)
   1463 
   1464     def train_on_batch(self, x, y,
 
/usr/local/lib/python3.6/dist-packages/keras/engine/training_arrays.py in predict_loop(model, f, ins, batch_size, verbose, steps, callbacks)
    322             batch_logs = {'batch': batch_index, 'size': len(batch_ids)}
    323             callbacks._call_batch_hook('predict', 'begin', batch_index, batch_logs)
--> 324             batch_outs = f(ins_batch)
    325             batch_outs = to_list(batch_outs)
    326             if batch_index == 0:
 
/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3474 
   3475     fetched = self._callable_fn(*array_vals,
-> 3476                                 run_metadata=self.run_metadata)
   3477     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3478     output_structure = nest.pack_sequence_as(
 
/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
 
ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,61,1440,1920,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node conv3d_31/convolution}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 
         [[dist_2/add/_665]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 
  (1) Resource exhausted: OOM when allocating tensor with shape[1,61,1440,1920,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node conv3d_31/convolution}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 
0 successful operations.
0 derived errors ignored.

**Comment by guijacquemet** [comment]
Hello,
Many thanks for reaching out!
The "Resource exhausted" error is indeed an indication that the file/patch size is too big. But to help you more I would need to know:
- What notebook are you trying to use?
- What are the dimension and size of the images/stacks you want to use?

Cheers
Guillaume

**Comment by Nal44** [comment]
Hi Guillaume.
THanks for the answer.
I am using Stardist 3D notebook.
My test image is a 1 channel stack of 61 slices (DAPI) , 197,62x148,21 microns (1920x1440) 8 bits. 

Basically, I want to detect all nucleus in the image then get all ROIs then perform others steps once the nuclei has been segmented.

PS: let me know if you need anything else
THanks a lot :)
Antho

**Comment by guijacquemet** [comment]
Hi Antho,
Thanks a lot. yes, the issue is that your image size is large and it does not fit in the RAM.
By default, the notebook tries to load the whole stack as a single patch. To make it work, you need to disable the default options and choose a smaller patch_size  and patch_height. try to decrease these values until the OOM error disappear. Maybe start around 400 (patch_size) and 68 (patch_height). Once you have found suitable values, you could split your training dataset into smaller images so that you can use the default parameters.

**Comment by Nal44** [comment]
Hi.
Ok thanks Ill try that ,
Cheers !
antho

**Comment by guijacquemet** [comment]
Let us know how it goes!

**Comment by Nal44** [comment]
Just to make clear : 
The issue comes from the training set (which worked perfectly) OR the image I want to predict using the training set ?
Thanks

**Comment by Nal44** [comment]
I reduced the size of my testing image (crop to 250x250) and it worked.
Now I will re train a new set using my own images on try again.

If I crop my images into small pieces, it is possible to re-assemble them after the predictions are made in the same exact order?

**Comment by guijacquemet** [comment]
Ok, now I think I misunderstood your issue. 
Just to clarify. Did you train the network with your own images or the one that are provided (link provided)?
From your last post, it sounds like you have used the one provided by the original stardist authors, and that you are having the OOM error during the prediction (Step6).
Is this the case?
If it is the case you should be able to input much larger images than 250x250.
Also, I can check if we can implement tiling for the prediction step directly in the notebook

**Comment by Nal44** [comment]
Hi,

yes :
I trained the network with the one provided  (https://github.com/mpicbg-csbd/stardist/releases/download/0.3.0/demo3D.zip)

Then used my own image (the large one: 1 channel 61 image stack  1440x1920 ) to test the prediction and the  OOM error occurred during the prediction (Step6).

I can upload the image onto the drive if you want to test on your side ?

I hope I am explaining right :)

Thanks a lot!
Antho

**Comment by guijacquemet** [comment]
Ok, I am with you now.
I have added the possibility to do tiling for the prediction step directly in the notebook. 
The feature will be available with the next release. You will be able to choose the number of tiles that will be used to divide your images. Each tile will then be processed independently and re-assembled to generate the final image.
This should fix your issue.

**Comment by Nal44** [comment]
Great !!
Thanks a lot,
Cheers :)

**Comment by guijacquemet** [comment]
Hi,
We have now released a new version of Stardist 3D where you can choose the number of tiles that you want to use to perform predictions.
This should solve your issue!
Let us know how if it works for you!
Cheers
Guillaume

**Comment by Nal44** [comment]
Great!
Thanks a lot,
Cheers :)
antho
